# To get started with Dependabot version updates, you'll need to specify which package ecosystems to update and
# where the package manifests are located. Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
registries:
    dhi:
        type: docker-registry
        url: https://dhi.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_READONLY_PASSWORD }}
updates:
    - package-ecosystem: npm
      directory: .
      open-pull-requests-limit: 10
      versioning-strategy: lockfile-only
      schedule:
          interval: weekly
      groups:
          angular:
              patterns:
                  - '@angular'
          vitest:
              patterns:
                  - 'vitest'
                  - 'vite'
                  - '@vitest'
                  - 'playwright'
          prettier:
              patterns:
                  - 'prettier'
          eslint:
              patterns:
                  - 'angular-eslint'
                  - '@angular-eslint'
                  - '@eslint'
                  - 'eslint'
                  - 'typescript-eslint'
          stylelint:
              patterns:
                  - 'stylelint'

    - package-ecosystem: docker
      directory: .docker
      registries:
          - dhi
      schedule:
          interval: weekly

    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
